게임매니저 & 좀비 스포너 리팩토링, 유니티 테스트 프레임워크 버전 충돌 오류 해결
- 기존 좀비 스포너 로직 스크립트가 불필요한 책임이 많은 것 같아서 리팩토링함.

- 좀비 wave 설정을 게임 매니저 및 이벤트로 옮김.

- 좀비 사망 처리도 좀비 스포너에서 담당중인 상태인데, 이것도 수정 예정.

- manifest.json에서 Test Framework 버전 명시 후 재실행해서 해결

- Unity Test FrameWork를 Package Manager에서 Remove로 초기화 해줌

[ 에러 내역 ]
An error occurred while resolving packages: Project has invalid dependencies: com.unity.test-framework: Package [com.unity.test-framework@1.5.1] cannot be found

Library\PackageCache\com.unity.ide.visualstudio@198cdf337d13\Editor\Testing\TestAdaptor.cs(3,19): error CS0234: The type or namespace name 'TestTools' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

<참고사항>

- 학교 수업 때 프로젝트 코드 작성하면서 교재에 명시되어있는 버전과 처음부터 다른 버전을 사용했음.

- 해당 프로젝트 교재의 모든 예제는 유니티 2023.2 를 기준으로 만드록 유니티 6 베타에서 테스트했다고 함.
프로젝트 예제 파일 다운로드한 버전 그대로 사용 중. (Unity 6000.0.36.f1)

- 현재 브랜치의 바로 이전 커밋에선 처음에 로드해둔 에셋 버전과 안 맞는다는 경고가 떠서 6000.0.53.f1 으로 했었는데, 이후에 다시 프로젝트 원본 버전은 6000.0.36.f1 이었다. 그래서 다시 원본 버전에 맞게 사용중이다.

아마 프로젝트 파일을 다른 기기에서 로드하고 여러 원본과 수정파일을 덮어씌우면서 생긴 충돌 같다.

아무래도 기록 없이 파일을 교체한 상황에서 명확한 원인을 생각하는 건 무의미한 것 같다. 추론이 맞는지 증명할 수가 없을 것 같기 때문이다.